x-tanym-common: &tanym-common
  image: tanym/${CONTAINER_PREFIX}tanym
  platform: linux/amd64
  container_name: ${CONTAINER_PREFIX}tanym
  restart: always
  privileged: true
  tty: true
  stdin_open: true
  hostname: tanym
  environment:
    - APP_NAME=${APP_NAME}
    - NODE_ENV=${NODE_ENV}
    - RAILS_ENV=${RAILS_ENV}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    - REDIS_PASSWORD=${REDIS_PASSWORD}

services:
  tanym:
    <<: *tanym-common
    build:
      context: .
      dockerfile: docker/tanym/Dockerfile
    command: bin/rails s -b 0.0.0.0 -p 3000
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: tanym/${CONTAINER_PREFIX}tanym/postgres
    sysctls:
      net.core.somaxconn: 65535
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
    platform: linux/amd64
    container_name: ${CONTAINER_PREFIX}tanym-postgres
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  redis:
    image: tanym/${CONTAINER_PREFIX}tanym/redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    platform: linux/amd64
    container_name: ${CONTAINER_PREFIX}tanym-redis
    restart: always
    command: redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      # Redis configuration file example: https://redis.io/docs/management/config-file/
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

